### ISSUE TITLE
Change shell types to cross-platform compatible ones

### ISSUE THREAD

**Issue by FlorianBeerRB** [LieberLieber/LemonTree.Automation.Workflows#13]
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
Windows/Linux compatible shells are

- bash
- pwsh
- python

pwsh should be close to powershell as it's just core instead of desktop version of powershell

**Comment by FlorianBeerRB** [comment]
Our runner doesn't support pwsh

**Comment by danielsiegl** [comment]
@aschoelzhorn will evaluate if we can update our agents without destroying something

**Comment by danielsiegl** [comment]
@FlorianBeerRB  @aschoelzhorn installed pwsh on our Agent LLBUILD10 - I validated with remote desktop that it is there.
