### ISSUE TITLE
Update review session file is having password issue

### ISSUE THREAD

**Issue by FlorianBeerRB** [LieberLieber/LemonTree.Automation.Workflows#17]
Writing session file 'SysEngAutomationTest-PR-15-cd41f182d20f59b07187a1db72c78b45cd6076ee-aeed18c6544d519b2a5c262208f4f3ddc56c0289.ltsfs'...
Finished Diff
Uploading sessionfile to artifactory: https://lieberlieber.jfrog.io/artifactory/lemontree-generic-local/SysEngAutomationTest-PR-15-cd41f182d20f59b07187a1db72c78b45cd6076ee-aeed18c6544d519b2a5c262208f4f3ddc56c0289.ltsfs
Enter host password for user 'daniel':
Error: The operation was canceled.

**Comment by FlorianBeerRB** [comment]
Workflow is triggered each time when a pull request is open and a new commit is pushed to the target branch.
I've disabled the workflow until the topic is solved

**Comment by danielsiegl** [comment]
Tested with https://github.com/LieberLieber/LemonTree.Automation.Workflows/pull/19 and it seems to work! 
It creates a second comment for session file and it is working!

**Comment by FlorianBeerRB** [comment]
See comment on #29
