### ISSUE TITLE
Add Pipeline Tools

### ISSUE THREAD

**Issue by danielsiegl** [LieberLieber/LemonTree.Automation.Workflows#3]

**Comment by FlorianBeerRB** [comment]
Setting filters
Publishing to ProCloud

**Comment by danielsiegl** [comment]
I am a bit uncertain if we should build them on every commit or we make a /tools directory and a /src directory

**Comment by FlorianBeerRB** [comment]
I would host the binaries on artifactory (or some other https:// ) and download for every use.
If the files are larer, we should check out some caching functionality.
But I would not host the tools in the same repo than our code (or we have to include a LemonTree bugfix in all open model branches whne in production

**Comment by danielsiegl** [comment]
@FlorianBeerRB If I add the source we need to build them on every action run that needs em... I am unsure how to proceed

**Comment by danielsiegl** [comment]
But it would be kinda cool to host the code of the tools in the same repo? or should I create a seperate repo?

**Comment by danielsiegl** [comment]
@FlorianBeerRB 
First 2 are on Nexus:
https://nexus.lieberlieber.com/#browse/browse:lemontree-pipeline-tools

https://nexus.lieberlieber.com/repository/lemontree-pipeline-tools/LemonTree.Pipeline.Tools.RemovePrerenderedDiagrams.exe
https://nexus.lieberlieber.com/repository/lemontree-pipeline-tools/LemonTree.Pipeline.Tools.SetFilterInSessionFile.exe

**Comment by danielsiegl** [comment]
Seperate Repository: https://github.com/LieberLieber/LemonTree.Pipeline.Tools
