### ISSUE TITLE
OnDemand deployment without installation

### ISSUE THREAD

**Issue by FlorianBeerRB** [LieberLieber/LemonTree.Automation.Workflows#31]
No local installation of LemonTree.Automation

- Binaries via xcopy / docker
- license via access token and command line

**Comment by danielsiegl** [comment]
This is part of the LemonTree.Automation 3.3 release!
@aschoelzhorn and his Team will provide:
* Zip Download (Docker only makes sense when EA 16 is primetime and on Linux we will not support EAP(X) just (QEA(X)
* support for RLM License Server aka Floating licensing
* And a way to pace the license via a commandline

**Comment by danielsiegl** [comment]
@aschoelzhorn @paulkronabethleitner  we should provide a script on this repo that shows how it is done!

**Comment by danielsiegl** [comment]
It is coming with LT 3.3 Release so I Close this Issue - to create a Demo Showcasing is part of: https://github.com/LieberLieber/LemonTree.Automation.Workflows/issues/77
