### ISSUE TITLE
Use LTA to Update a branch if no "real" conflict has been found.

### ISSUE THREAD

**Issue by danielsiegl** [LieberLieber/LemonTree.Automation.Workflows#43]
The Scenario:
* file level conflict
* no model level conflict

==> LTA could automatically merge when we click resolve:

![image](https://user-images.githubusercontent.com/41949368/161445115-bbc876b8-b833-4d64-a9ed-fbe7a409327c.png)

**Comment by danielsiegl** [comment]
Seems not super easy because of GitHub beeing GitHub:

**Comment by danielsiegl** [comment]
More Info: https://baywet.github.io/pull-request-conflict-github-workflow/

**Comment by danielsiegl** [comment]
I would not want to run the conflict resolution without the user interaction

**Comment by danielsiegl** [comment]
@FlorianBeerRB your toughts?

**Comment by danielsiegl** [comment]
Funny Idea - creating a specific comment triggers an action that we could use to "rebase" or "merge" the model in the PR.

**Comment by FlorianBeerRB** [comment]
[TriggerMergeByComments.yml](https://github.com/LieberLieber/LemonTree.Automation.Workflows/blob/main/.github/workflows/TriggerMergeByComments.yml) does this job
Try `/merge/` as comment

**Comment by danielsiegl** [comment]
the current problem is that one file has 1kb

![image](https://user-images.githubusercontent.com/41949368/162299477-4123e5da-fa74-4fe2-bfea-188c32a910fc.png)


I added artifact download to the action

**Comment by danielsiegl** [comment]
Seems to be an LFS Issue Artifact can be found here. https://github.com/LieberLieber/LemonTree.Automation.Workflows/actions/runs/2111439906

**Comment by danielsiegl** [comment]
I create an Issue for LemonTree.Automation to deflate LFS as part of the automation

**Comment by FlorianBeerRB** [comment]
creation of commit works, but push is not working
@danielsiegl please investigate on the runner directly

**Comment by danielsiegl** [comment]
Working on it - https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action

**Comment by danielsiegl** [comment]
The push is solved now - it needs the PAT Token as authentication
