### ISSUE TITLE
Restrict merge by comment to specific user groups

### ISSUE THREAD

**Issue by FlorianBeerRB** [LieberLieber/LemonTree.Automation.Workflows#45]
github.event.comment.author_association == 'MEMBER'. See [documentation](https://developer.github.com/v4/enum/commentauthorassociation/) for a list of all available values of author_association.

could be used to strict trigger by comment to specific user groups

**Comment by danielsiegl** [comment]
Good Idea.

**Comment by FlorianBeerRB** [comment]
Current idea after some investigations:
https://docs.github.com/en/enterprise-server@3.3/actions/using-jobs/defining-outputs-for-jobs
- First job checking permission and posting "Insufficient permission" message if needed
- 2nd job running the merge

value in my local test repo COLLABORATOR
need some construct with contains(list, value)

**Comment by FlorianBeerRB** [comment]
Add "PR approved" as criterion

**Comment by FlorianBeerRB** [comment]
resolved with aa1f6f4

**Comment by FlorianBeerRB** [comment]
6a208167 now has also messages for status
