### ISSUE TITLE
Rebasing a Model in a Branch from a Pull Request

### ISSUE THREAD

**Issue by danielsiegl** [LieberLieber/LemonTree.Automation.Workflows#54]
/Merge/ will merge an close a pullrequest - I guess we should also have a version that does a "rebase" of the model in the branch but keeps the Pullrequest/Branch active.

==> Models will still be binary different (== not possible to close the branch)- but the model contents form "main" would be moved up into the feature branch.

**Comment by FlorianBeerRB** [comment]
It's basically the same, just A and B are switched...
