### ISSUE TITLE
Auto Deploy LemonTree Automation Demo via .zip file

### ISSUE THREAD

**Issue by danielsiegl** [LieberLieber/LemonTree.Automation.Workflows#77]
We need to add a Workflow/Action that demonstrates how to deploy LemonTree.Automation on an Agent in an automated fashion without using the .msi installer.

**Comment by FlorianBeerRB** [comment]
Maybe dockerizing LemonTree.Automation on a windows nanoserver is a good option
https://blog.sixeyed.com/how-to-dockerize-windows-applications/
https://hub.docker.com/_/microsoft-windows-nanoserver

**Comment by danielsiegl** [comment]
I guess that would perfect to create an Action for GitHub Marketplace.
Similar Actions exist for Nuget and MSBuild

**Comment by FlorianBeerRB** [comment]
We can create a local action in the repository and then later publish it on marketplace

**Comment by danielsiegl** [comment]
@aschoelzhorn  I created a temporary upload
https://nexus.lieberlieber.com/#browse/browse:lemontree-release:LemonTree.Automation%2FLemonTree.Automation.Zip_Deploy.zip
