### ISSUE TITLE
/rebase/ not working

### ISSUE THREAD

**Issue by danielsiegl** [LieberLieber/LemonTree.Automation.Workflows#78]
It seems somehow our way to trigger stuff with comments is not working anymore:
https://github.com/LieberLieber/LemonTree.Automation.Workflows/pull/75#issuecomment-1102492359

Resulted in:
https://github.com/LieberLieber/LemonTree.Automation.Workflows/actions/runs/2189115274

**Comment by FlorianBeerRB** [comment]
fixed with commit 10d1fc54
