### ISSUE TITLE
Nexus not sending data

### ISSUE THREAD

**Issue by FlorianBeerRB** [LieberLieber/LemonTree.Automation.Workflows#81]
![image](https://user-images.githubusercontent.com/72773721/164127000-64d77a23-fd3e-46d8-b56f-9bab0183777c.png)

**Comment by danielsiegl** [comment]
Hi,
Maybe it was just the URL Escaping in the Email:
So can you pls test:
https://nexus.lieberlieber.com/#browse/browse:lemontree-session

and
https://nexus.lieberlieber.com/repository/lemontree-session/LemonTree.Automation.Workflows-PR-72-6424d751430d8c3a1287c2f77e2c11aecd01cac8-f99df0b430caca2efd7720dce3fb38ff2f0566ce.ltsfs

Both work for us.

Cheers
Daniel

**Comment by FlorianBeerRB** [comment]
Works from outside Bosch network, seems to be a proxy issue

**Comment by danielsiegl** [comment]
Do you think it is fixable - this shall also serve as our docker hub!

**Comment by FlorianBeerRB** [comment]
Nope, weder vom Firmenlaptop noch vom privaten Handy aus

Best regards,

Florian Beer

Engineering Driving Systems 2G (XC-DX/EDY2-JP)
Bosch Corporation | 3-6-7, Shibuya, Shibuya-ku | Tokyo 150-8360 | JAPAN | www.bosch.co.jp
Tel. +81 45 912-6694 | Mobile +81 70 7595-5554 | Fax +49 711 811 | ***@***.******@***.***>
​
